config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :messages
  resources :foodtrucks do
    resources :messages
    resources :reviews
  end

  get '/' => 'users#log_in'#creates log in as home page

  get 'users/profile' => 'users#profile', as: :profile
  get 'users/log_in' => 'users#log_in', as: :log_in
  resources :users, only: [:new, :create]

  resources :sessions, only: [:create, :destroy]
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

end

app/models/foodtruck.rb
class Foodtruck < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :foodtruck
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :foodtruck
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :foodtrucks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foodtrucks_controller.rb
class FoodtrucksController < ApplicationController

  def index
    @foodtrucks = Foodtruck.all
  end

  def show
    @foodtruck = Foodtruck.find(params[:id])
    @message = Message.new
    @message.foodtruck_id = @foodtruck.id
    @review = Review.new
    @review.foodtruck_id = @foodtruck.id
  end

  def new
    @foodtruck =  Foodtruck.new
  end

  def create
    @foodtruck = Foodtruck.create(foodtruck_params)
    redirect_to foodtrucks_path
  end

  def edit
    @foodtruck = Foodtruck.find(params[:id])
    @message = Message.find_by(foodtruck: params[:id])
  end

  def update
    @foodtruck = Foodtruck.find(params[:id])
    @foodtruck.update(foodtruck_params)

    redirect_to foodtrucks_path(@foodtruck)
  end

  def destroy
    @foodtruck = Foodtruck.find(params[:id])
    @foodtruck.destroy

    redirect_to foodtrucks_path
  end


end

private

  def foodtruck_params
    params.require(:foodtruck).permit(:name, :img_url, :card, :menu, :cuisine)
  end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
    @message = Message.new(message_params)
    @message.foodtruck_id = params[:foodtruck_id]

    @message.save

    redirect_to foodtruck_path(@message.foodtruck)
  end

  def message_params
    params.require(:message).permit(:body)
  end

  def show
  end

  def edit
    @message.id
  end
  
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index

  end


  def new
  end

  def create
    @review = Review.new(review_params)
    @review.foodtruck_id = params[:foodtruck_id]

    @review.save
    redirect_to foodtruck_path(@review.foodtruck)
  end

  def show
  end

  def review_params
    params.require(:review).permit(:author, :rating, :message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    username = params[:username]
    password = params[:password]
    user = User.find_by({username: username})
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to foodtrucks_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include SessionsHelper

  def create
    User.create(user_params)
    redirect_to log_in_path
  end

  def new
    @user = User.new
  end

  def profile
    authenticate
    @user = current_user
  end

  def index
  end

  def show
  end

  def log_in

  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodtrucks_helper.rb
module FoodtrucksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def authenticate
      redirect_to log_in_path unless current_user
  end

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foodtrucks/_form.html.erb
<%= form_for(@foodtruck) do |f| %>

  <p>
    <%= f.label :name, "Streatery Name" %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :img_url, "Image" %>
    <%= f.text_field :img_url %>
  </p>
  <p>
    <%= f.label :cuisine, "Cuisine" %>
    <%= f.text_field :cuisine %>
  </p>
  <p>
    <%= f.label :card, "Accept Cards" %>
    <%= f.text_field :card %>
  </p>
  <p>
    <%= f.label :menu, "Menu" %>
    <%= f.text_field :menu %>
  </p>
  <div class="submit_button">  
    <%= f.submit 'New Streatery', class= "btn btn-success" %>
  </div>





  <% end %>

app/views/foodtrucks/_message.html.erb
<h3>Post to Message Board</h3>

<p>Posted <%= distance_of_time_in_words(message.foodtruck.created_at, message.created_at) %>later</p>
<div>
  <p class="message"><%= message.body %></p>
</div>

app/views/foodtrucks/_review.html.erb
<div>
  <h4>Review by <%= review.author %></h4>
  <p class="text-center"><%= review.message %></p>
</div>

app/views/foodtrucks/edit.html.erb
<div class="text-center text-info">
  <h1>Edit Streatery</h1>
</div>

<div class="text-center text-primary">

<%= form_for @foodtruck do |f| %>

  <%= f.label :name, "Streatery Name" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :img_url, "Image or Logo" %>
  <br>
  <%= f.text_field :img_url %>
  <br>
  <br>
  <%= f.label :cuisine %>
  <br>
  <%= f.text_field :cuisine %>
  <br>
  <br>
  <%= f.label :card, "Accepts Cards" %>
  <br>
  <%= f.text_field :card %>
  <br>
  <br>
  <%= f.label :menu, "Menu Favorites" %>
  <br>
  <%= f.text_field :menu %>
  <br>
  <br>
  <br>
  <br>
  <%= f.submit 'Update', class: "btn btn-info" %>
  <br>
  <br>

<% end %>
</div>
<br>
<div class="text-center">

<%= button_to 'Delete Truck', "/foodtrucks/#{@foodtruck.id}", method: "delete", class: "btn btn-danger" %>
</div>

app/views/foodtrucks/index.html.erb
<h1 class="text-center">s  t  r  [ e a t ]  e  r  y</h1>

<div class="container-fluid">

  <div class="row">
    <% @foodtrucks.each do |foodtruck| %>
    <div class="col-md-4">

    <h2 class="text-center"><a href="/foodtrucks/<%= foodtruck.id %>"><%= foodtruck.name %></a></h2>
      <img src="<%= foodtruck.img_url %>", width="300", height="200", class="center-block img-rounded">
      <p class="text-center">Cuisine: <%= foodtruck.cuisine %></p>
      <p class="text-center">Accepts Cards: <%= foodtruck.card %></p>
      <p class="text-center">Menu: <%= foodtruck.menu %></p>
    <br>
    <br>

    </div>
    <% end %>
  </div>
</div>




<%= button_to 'CREATE NEW STREATERY', "/foodtrucks/new", method: "get", class: 'btn btn-info btn-block' %>

app/views/foodtrucks/new.html.erb
<h1 class="text-center text-info">Create Streatery</h1>
<div class="text-center text-primary">

<%= form_for @foodtruck do |f| %>

  <%= f.label :name, "Streatery Name" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :img_url, "Image or Logo" %>
  <br>
  <%= f.text_field :img_url %>
  <br>
  <br>
  <%= f.label :cuisine %>
  <br>
  <%= f.text_field :cuisine %>
  <br>
  <br>
  <%= f.label :card, "Accepts Cards" %>
  <br>
  <%= f.text_field :card %>
  <br>
  <br>
  <%= f.label :menu, "Menu Favorites" %>
  <br>
  <%= f.text_field :menu %>
  <br>
  <br>
  <br>
  <%= f.submit 'GENERATE STREATERY', class: "btn btn-info" %>

<% end %>

</div>

app/views/foodtrucks/show.html.erb
<div class="text-center">

  <h1 class="text-primary"><%= @foodtruck.name %></h1>

</div>


    <img src="<%= @foodtruck.img_url %>", width="400", height="300", class="center-block img-rounded", >


  <%= render partial: 'messages/form' %>
<div class="text-center">

        <% @foodtruck.messages.each do |message| %>
        <p><%= message.body %></p>
        <% end %>
</div>


<br>
<br>
<br>
<br>



  <%= render partial: 'reviews/form' %>

<div class="text-center">

        <% @foodtruck.reviews.each do |review| %>
        <p><%= review.author %></p>
        <p><%= review.rating %></p>
        <p><%= review.message %></p>
        <% end %>
</div>

<br>
<br>

<div id=buttons_view, class="text-center">

    <button class="btn btn-default btn-lg" <h3><a href="/foodtrucks">View All</a></h3></button>

</div>
<br>
<div id=button_edit, class="text-center">

    <button class="btn btn-default btn-lg", <h3><%= link_to "Edit Streatery", edit_foodtruck_path(@foodtruck) %></h3></button>

</div>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streatery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<div class="text-center">

<%= form_for [ @foodtruck, @message ] do |f| %>
  <p class="text-warning">
    <% f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Update', class: "btn btn-info" %>
  </p>
<% end %>
</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/messages/show.html.erb
<h3>Message Board</h3>
<%= render partial: 'foodtrucks/message', collection: @foodtruck.messages %>

app/views/reviews/_form.html.erb
<div class="text-center">

  <h3 class=text-warning>Review Board</h3>
    <h5 class="text-muted">Reviews (<%= @foodtruck.reviews.size %>)</h5>
  <br>
      <%= form_for [ @foodtruck, @review ] do |f| %>

          <p class="text-warning text-center">
            <%= f.label :author %>
            <br/>
            <%= f.text_field :author %>
          </p>

          <p class="text-warning text-center">
            <%= f.label :message %>
            <br/>
            <%= f.text_area :message %>
          </p>


          <p class="text-info">
            <%= f.submit 'Post Review', class: "btn btn-info" %>
          </p>

      <% end %>


</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/log_in.html.erb
<h1 class="text-center text-info">s t r [ e a t ] e r y</h1>

<div class="text-center">

      <br>
      <br>

  <div class="text-primary">

    <%= form_tag '/sessions', method: :post do %>

      <%= label_tag :username %>

        <br>

      <%= text_field_tag :username %>

        <br>

      <%= label_tag :password %>

        <br>

      <%= password_field_tag :password %>

        <br>
        <br>

</div>

    <div class="text-info">

      <%= submit_tag "Log In" %>

    </div>

        <% end %>

        <br>
        <br>


  </div>


<div class="text-center text-info">

<%= button_to 'Sign Up', "/users/new", method: "get" %>

</div>

app/views/users/new.html.erb
<div class="text-center text-info">

<h1>Sign Up</h1>

</div>

<div class="create_new_user text-center">

<%= form_for @user do |f| %>
<p class="text-primary">

    <%= f.label :username, "Username"%>
    <br>
    <%= f.text_field :username%>

</p>

<p class="text-primary">

    <%= f.label :password, "Password"%>
    <br>
    <%= f.password_field :password%>

</p>

<p class="text-primary">

    <%= f.label :password_confirmation, "Confirm Password"%>
    <br>
    <%= f.password_field :password_confirmation%>

</p>
<br>
<br>
    <%= f.submit%>

<%end%>

</div>

</div>

app/views/users/profile.html.erb
<h3>Welcome Back <%= @user.username %></h3>

<%= button_to "Log Out", '/sessions', method: :delete %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>